apiVersion: v1
kind: Service
metadata:
  name: nats-lb
  namespace: {{ include "vechr.namespace" . }}
  {{if .Values.gke.enabled}}
  annotations:
    cloud.google.com/l4-rbs: "enabled"
  {{end}}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nats
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
      name: nats
    - protocol: TCP
      port: 1833
      targetPort: 1833
      name: mqtt
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: websocket
  {{if .Values.gke.enabled}}
  loadBalancerIP: {{ .Values.gke.nats.loadBalancerIP | quote }}
  externalTrafficPolicy: Cluster
  {{end}}