{{if .Values.common.frontend.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: vechr-frontend-{{ .Values.common.frontend.name }}
  namespace: {{ include "vechr.namespace" . }}
  labels:
    app: vechr-frontend-{{ .Values.common.frontend.name }}
spec:
  type: NodePort
  selector:
    app: vechr-frontend-{{ .Values.common.frontend.name }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.common.frontend.externalPort }}
      targetPort:  {{ .Values.common.frontend.port }}
      nodePort: {{ .Values.common.frontend.nodePort }}

{{end}}